name: nodejs
type: nodejs
deployment:
  tasks:
    - export NODE_ENV=production
    - cd /home/saqiicod/invoice.saqiicoditz.online
    - /opt/cpanel/ea-nodejs18/bin/npm install
    - touch tmp/restart.txt
